function L = paint_line_gouraud(edges, active_edges_nums, y, x1_active, x2_active, img)

        %% use vector interpolation to find the colors of the active points
        x1_active_color = vector_interp(   edges(active_edges_nums(1)).vertices(1, 1:2), ...
                                                                        edges(active_edges_nums(1)).vertices(2, 1:2), ...
                                                                        [x1_active, y], ...
                                                                        edges(active_edges_nums(1)).vertex_color(1, 1:3), ...
                                                                        edges(active_edges_nums(1)).vertex_color(2, 1:3), ...
                                                                        2   );

        x2_active_color = vector_interp(   edges(active_edges_nums(2)).vertices(1, 1:2), ...
                                                                        edges(active_edges_nums(2)).vertices(2, 1:2), ...
                                                                        [x2_active, y], ...
                                                                        edges(active_edges_nums(2)).vertex_color(1, 1:3), ...
                                                                        edges(active_edges_nums(2)).vertex_color(2, 1:3), ...
                                                                        2   );

        %% paint the line between active x bounds using vector interpolation
        x_min = floor(min(x1_active, x2_active) + 0.5);
        x_max = floor(max(x1_active, x2_active) + 0.5);
        L = img(x_min:x_max, y, 1:3);

        for x = x_min:x_max
            color = vector_interp(   [x1_active, y], ...
                                                        [x2_active, y], ...
                                                                        [x, y], ...
                                                    x1_active_color, ... 
                                                    x2_active_color, ...
                                                      1  ); 
           L(x - x_min + 1, 1, 1:3) = color;
        end
end